export const LOAD_TASKS_REQUEST = "@tasks/LOAD_TASKS_REQUEST";
export const LOAD_TASKS_SUCCESS = "@tasks/LOAD_TASKS_SUCCESS";
export const LOAD_TASKS_FAILURE = "@tasks/LOAD_TASKS_FAILURE";

export const UPDATE_TASK_REQUEST = "@tasks/UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "@tasks/UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "@tasks/UPDATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "@tasks/DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "@tasks/DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "@tasks/DELETE_TASK_FAILURE";

export const CREATE_TASK_REQUEST = "@tasks/CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "@tasks/CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "@tasks/CREATE_TASK_FAILURE";
