export const LOAD_COLUMNS_REQUEST = "@columns/LOAD_COLUMNS_REQUEST";
export const LOAD_COLUMNS_SUCCESS = "@columns/LOAD_COLUMNS_SUCCESS";
export const LOAD_COLUMNS_FAILURE = "@columns/LOAD_COLUMNS_FAILURE";

export const UPDATE_COLUMN_REQUEST = "@columns/UPDATE_COLUMN_REQUEST";
export const UPDATE_COLUMN_SUCCESS = "@columns/UPDATE_COLUMN_SUCCESS";
export const UPDATE_COLUMN_FAILURE = "@columns/UPDATE_COLUMN_FAILURE";
